### ISSUE TITLE
chezmoi how-to video feedback

### ISSUE THREAD

**Issue by twpayne** [bketelsen/dotfiles#1]
Thanks for the [nice how-to video on using chezmoi on YouTube](https://www.youtube.com/watch?v=HXx6ugA98Qo)!

A few notes:

You can automate the installation of vim plugins by running:

    vim -c PlugUpdate -c qa

This tells VIM to run `PlugUpdate` and then `qa` (quit).

The "strange location" `~/.local/share/chezmoi` for the dotfiles repo is for compatibility with the [XDG base directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

This command failed for you:

    chezmoi git commit -m"remove bootstrap"

The reason is that the `-m` option was interpreted by chezmoi (which didn't recognize it) instead of being passed through to `git commit`. You need to add a `--` which stops chezmoi from consuming any more arguments so they can be passed to `git commit`, i.e.:

    chezmoi git commit -- -m"remove bootstrap"

The `run_once_` scripts are run whenever their contents change.

Hope this helps, and thanks again for the video :)

**Comment by bketelsen** [comment]
Thank you so much for the feedback @twpayne !  I'm working on getting my dotfiles ready for Visual Studio Codespaces today and I'll incorporate these changes.

I appreciate chezmoi, thanks for making it.
